name: Deploy to Rinkeby

on:
  workflow_dispatch

jobs:
  upgrade-rinkeby:
    name: Deploy To Rinkeby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Node.js version #https://github.com/actions/setup-node/pull/338
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: 'yarn'
      - name: Install modules
        run: yarn install
      - name: Upgrade contract
        env:
          DEFENDER_TEAM_API_KEY: ${{ secrets.DEFENDER_TEAM_API_KEY }}
          DEFENDER_TEAM_API_SECRET_KEY: ${{ secrets.DEFENDER_TEAM_API_SECRET_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
          ROPSTEN_URL: ${{ secrets.ROPSTEN_URL }}
        run: yarn upgrade:rinkeby
